#!/bin/sh -e

# iw manpage is extremely small, 
# we don't need to compress it.
clsed 's@\(iw\.8\)\.gz@\1@' Makefile

make \
    DESTDIR="$1" \
    LDFLAGS="$LDFLAGS -static" \
    CFLAGS="$CFLAGS -I/usr/include/libnl-tiny -DCONFIG_LIBNL20 -D_GNU_SOURCE" \
    NL1FOUND="" NL2FOUND=Y NLLIBNAME=libnl-tiny \
    LIBS=-lnl-tiny \
    PREFIX="/usr" \
    SBINDIR="/usr/bin" \
    install
