#!/bin/sh -e

# There is a problem with the archive format so we can't extract it with pax.
busybox tar -xJ --strip-components 1 -f "ruby-$2.tar.xz?no_extract"

# This build problem occurs in the latest libressl series, I don't exactly know
# if this is an issue with ruby or libressl, so below here is an absolute hack.
clsed '/#include "ossl.h"/r /dev/stdin' ext/openssl/ossl_pkey.c <<EOF
struct evp_pkey_st {
       int type;
       int save_type;
       int references;
       const EVP_PKEY_ASN1_METHOD *ameth;
       ENGINE *engine;
       union   {
               char *ptr;
#ifndef OPENSSL_NO_RSA
               struct rsa_st *rsa;     /* RSA */
#endif
#ifndef OPENSSL_NO_DSA
               struct dsa_st *dsa;     /* DSA */
#endif
#ifndef OPENSSL_NO_DH
               struct dh_st *dh;       /* DH */
#endif
#ifndef OPENSSL_NO_EC
               struct ec_key_st *ec;   /* ECC */
#endif
#ifndef OPENSSL_NO_GOST
               struct gost_key_st *gost; /* GOST */
#endif
       } pkey;
       int save_parameters;
       STACK_OF(X509_ATTRIBUTE) *attributes; /* [ 0 ] */
} /* EVP_PKEY */;
EOF

./configure \
    --prefix=/usr \
    --enable-shared \
    --enable-static \
    --disable-rpath

make
make DESTDIR="$1" install
