#!/bin/sh -e

clsed '43a #include <limits.h>' random/jitterentropy-base-user.h
clsed '44a #include <fcntl.h>'  random/jitterentropy-base-user.h

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --localstatedir=/var \
    --enable-static

make -j1
make DESTDIR="$1" install
