#!/bin/sh -e

./configure \
    --prefix=/usr \
    --localstatedir=/var \
    --bindir=/usr/bin \
    --sbindir=/usr/bin \
    --libdir=/usr/lib \
    --enable-libuuid \
    --enable-libblkid \
    --enable-fsck \
    --disable-makeinstall-chown \
    --disable-rpath \
    --without-udev \
    --without-python \
    --without-systemd

make
make DESTDIR="$1" install

# For some reason util-linux installs
# to the sbindir even when we tell it
# not to.
mv "$1/usr/sbin/"* "$1/usr/bin"
rm -rf "$1/usr/sbin"
