#!/bin/sh -e

export DESTDIR="$1"

cl-meson \
    -Dintrospection=enabled \
    -Djasper=false \
    -Dpng=true \
    -Ddocs=false \
    -Dman=false \
    -Dinstalled_tests=false \
    -Dbuiltin_loaders=all \
    . output

ninja -C output
ninja -C output install
