#!/bin/sh -e

[ "$CPT_CROSS_TRIPLET" ] && CC=$CPT_CROSS_TRIPLET-cc \
                            AR=$CPT_CROSS_TRIPLET-ar \
                            RANLIB=$CPT_CROSS_TRIPLET-ranlib

: "${CC:=cc}" "${AR:=ar}" "${RANLIB:=ranlib}"

make CC=$CC AR=$AR RANLIB=$RANLIB LDFLAGS="$LDFLAGS -static" sbase-box
make PREFIX=/usr DESTDIR="$1" sbase-box-install

unlink "$1/usr/bin/tar"
unlink "$1/usr/bin/sed"
