#!/bin/sh -e

export DESTDIR="$1"

cl-meson \
    -Dexamples=disabled \
    -Dlibseat-builtin=enabled \
    -Dman-pages=enabled \
    . output

ninja -C output
ninja -C output install

clsv seatd.run

chmod u+s "$1/usr/bin/seatd-launch"
