#!/bin/sh -e

./configure \
    --prefix=/usr \
    --enable-ipv6 \
    --enable-unix-sockets \
    --enable-hidden-symbols \
    --without-libidn \
    --without-libidn2 \
    --without-nghttp2 \
    --disable-manual \
    --disable-ldap \
    --disable-ares \
    --without-libidn \
    --without-librtmp \
    --without-icu \
    --without-libpsl \
    --with-openssl \
    --without-zstd \
    --with-pic

make
make DESTDIR="$1" install
rm -f src/curl
make LDFLAGS=-all-static
clinst -Dm755 src/curl "$1/usr/bin/curl"
