#!/bin/sh -e

make
make DESTDIR="$1" PREFIX=/usr install

ln -s minit "$1/usr/bin/init"

install -Dm755 -t "$1/usr/bin" reboot poweroff
install -Dm644 launch-services.boot "$1/etc/init/launch-services.boot"
install -Dm644 minit.post.shutdown "$1/etc/init/minit.post.shutdown"
