#!/bin/sh -e

export DESTDIR="$1"

[ "$CPT_TEST" ] && test=enabled

for plugin in libav good bad ugly; do (
    cd "$plugin"

    # Enable auto-features in gst-plugins
    cl-meson \
        --auto-features=auto \
        -Dexample=false \
        -Dtests=${test:-disabled} \
        -Dqt5=disabled \
        . output

    ninja -C output
    ninja -C output install
) done
