#!/bin/sh -e

# Modify Makefile to make it POSIX
sed -i '/^\.for/,/^\.endfor/d' Makefile

# Modify Makefile to properly use LDFLAGS
# We don't want this expression to expand
# shellcheck disable=2016
sed -i '/^kfcgi:/{n; s,$, $(LDFLAGS),}' Makefile

./configure \
    PREFIX=/usr \
    SBINDIR=/usr/bin \
    MANDIR=/usr/share/man \
    LDFLAGS="$LDFLAGS -static"

make
make DESTDIR="$1" install
