#!/bin/sh -e

# Forgive me father, for I have sinned.
(
    cd openssl

    ./Configure \
        --prefix=/usr \
        --openssldir=/etc/ssl \
        --libdir=lib \
        no-unit-test \
        no-shared \
        linux-x86_64

    make depend
    make

    make DESTDIR=$PWD/pkg install_sw
)

patch -p1 < python3-always-pip.patch

./configure \
    --prefix=/usr \
    --enable-shared \
    --enable-static \
    --with-system-expat \
    --with-system-ffi \
    --with-openssl="$PWD/openssl/pkg/usr" \
    --with-openssl-rpath=no \
    --with-ensurepip=yes

make
make DESTDIR="$1" install

ln -s python3 "$1/usr/bin/python"
ln -s pip3    "$1/usr/bin/pip"

# Make static library writable.
chmod -v u+w "$1/usr/lib/libpython"*
