#!/bin/sh -e

# Build and install busybox-init.
# This excludes utilities which require 'suid' to function.
make CC="${CC:-gcc}"
make CONFIG_PREFIX="$1/usr" install

mv "$1/usr/bin/busybox" "$1/usr/bin/busybox-init"

"$1/usr/bin/busybox-init" --list | while read -r bin; do
    ln -s busybox-init "$1/usr/bin/$bin"
done

install -Dm644 inittab "$1/etc/inittab"
