#!/bin/sh -e

export CFLAGS="$CFLAGS -fPIC"
export LDFLAGS="$LDFLAGS -static"

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --sysconfdir=/etc \
    --rundir=/run \
    --without-udev

make
make DESTDIR="$1" install

# Install services
clsv -d "$1" dhcpcd.run
