#!/bin/sh -e

sed_i() {
    for file; do :; done
    sed "$@" > _
    cat _ > "$file"; rm -f _
}

# Enable streaming related options if gstreamer is installed.
cpt-list gst-plugins-base >/dev/null 2>&1 && streaming=ON

# Enable the use of openjpeg if the package is installed.
cpt-list openjpeg2 >/dev/null 2>&1 && jpeg=ON

# Enable webcrypto if libtasn1 is installed.
cpt-list libtasn1 >/dev/null 2>&1 && libtasn=ON

patch -p1 < fix-musl.patch

# Remove gettext requirement.
sed_i 's/ngettext/printf/g' Tools/MiniBrowser/gtk/BrowserDownloadsBar.c
sed_i '/po_files \*\.po/d'  Source/WebCore/platform/gtk/po/CMakeLists.txt
sed_i '/^GETTEXT_C/d'       Source/WebCore/platform/gtk/po/CMakeLists.txt

# Fix wayland build.
sed -i '239,244d' Source/WebKit/WebProcess/InjectedBundle/InjectedBundle.cpp

# Fix clang build.
sed -i '/LC_ALL/d'       Source/JavaScriptCore/jsc.cpp
sed -i '/WTFLogAlways/d' Source/JavaScriptCore/jsc.cpp

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DLIB_INSTALL_DIR=/usr/lib \
    -DPORT=GTK \
    -DCMAKE_SKIP_RPATH=ON \
    -DENABLE_BUBBLEWRAP_SANDBOX=OFF \
    -DENABLE_SAMPLING_PROFILER=OFF \
    -DENABLE_GEOLOCATION=OFF \
    -DENABLE_GLES2=ON \
    -DENABLE_INTL=OFF \
    -DENABLE_INTROSPECTION=OFF \
    -DENABLE_MINIBROWSER=OFF \
    -DENABLE_OPENGL=OFF \
    -DENABLE_SPELLCHECK=OFF \
    -DENABLE_VIDEO=${streaming:-OFF} \
    -DENABLE_WEBGL=OFF \
    -DENABLE_WEB_AUDIO=${streaming:-OFF} \
    -DUSE_LIBHYPHEN=OFF \
    -DUSE_LIBNOTIFY=OFF \
    -DUSE_LIBSECRET=OFF \
    -DUSE_SYSTEMD=OFF \
    -DUSE_OPENJPEG=${jpeg:-OFF} \
    -DUSE_WOFF2=OFF \
    -DUSE_WPE_RENDERER=OFF \
    -DENABLE_WEB_CRYPTO=${libtasn:-OFF} \
    -DENABLE_MEDIASOURCE=${streaming:-OFF} \
    -Wno-dev

cmake --build   build
cmake --install build
