#!/bin/sh -e

yacc -o awkgram.tab.c -H awkgram.tab.h awkgram.y

make CFLAGS="$CFLAGS -static"
clinst -Dm755 "a.out" "$1/usr/bin/nawk"
ln -s /usr/bin/nawk "$1/usr/bin/awk"

mv awk.1 nawk.1
clman -d "$1" nawk.1
ln -s nawk.1 "$1/usr/share/man/man1/awk.1"
