#!/bin/sh -e

install -Dm755 kiss_path.sh "$1/etc/profile.d/kiss_path.sh"
make PREFIX=/usr DESTDIR="$1" install

printf '\033[1m%s\033[m\n' "" \
    "IMPORTANT" ""\
    "  Post installation will update to the latest version of the package manager: CPT" \
    "  This will automatically replace your /var/db/kiss directory to /var/db/cpt." \
    "  Please do NOT create the /var/db/cpt directory by yourself. The update will handle this." ""
