#!/bin/sh -e

cat <<EOF

[1mNEWS:[m Carbs Linux now uses its own fork of [1;33mkiss[m.
      You can visit <https://github.com/carbslinux/kiss>
      to inspect the changes.

[1mNOTE:
 
 [1;33mkiss [mand [1;33mkiss-utils[m packages have
 been merged. You can remove kiss-utils if you have
 it, and reinstall this package to use the upstream 
 contrib programs.

EOF
