#!/bin/sh -e

export DESTDIR="$1"
export LDFLAGS="$LDFLAGS -static"

patch -p1 < realpath-workaround.patch

cl-meson \
    -Dprefer_static=true \
    . output

ninja -C output
ninja -C output install
