#!/bin/sh -e

export LDFLAGS="$LDFLAGS -static"
patch -p1 < realpath-workaround.patch

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --localstatedir=/var \
    --with-priv-mode=none \
    --disable-man

make
make DESTDIR="$1" install
