#!/bin/sh -e

export LDFLAGS="$LDFLAGS -static"

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --disable-nls \
    --disable-rpath \
    --disable-device-mapper \
    "--with$(cpt l -C readline '' out)-readline"

# I hate it when build systems don't adhere to flags.
make CC="${CC:-cc} --static"
make DESTDIR="$1" install
