#!/bin/sh -e

docs=$(./src/cpt-list --check texinfo yes no)
make PREFIX=/usr "DOCS=$docs" DESTDIR="$1" install

install -Dm644 cpt-base "$1/etc/cpt-base"
install -Dm755 news     "$1/usr/bin/cpt-news"

install -Dm755 src/cpt "$1/usr/bin/cpt"
