#!/bin/sh -e

patch -p1 < busybox-style.patch

export LDFLAGS="$LDFLAGS -static"

./configure \
    --prefix=/usr \
    --enable-single-binary=symlinks \
    --with-packager="Carbs Linux" \
    --without-libgmp \
    --disable-libcap \
    --disable-nls

make
make DESTDIR="$1" install
