#!/bin/sh -e

export DESTDIR=$1

patch -p1 < remove_gettext.patch

# Fix build errors when appstream-glib or
# desktop-file-utils are installed.
clsed 's/appstream-util//'        data/meson.build
clsed 's/desktop-file-validate//' data/meson.build

cl-meson \
    -Dsynctex=disabled \
    . output
 
ninja -C output
ninja -C output install

clman zathura.1 zathurarc.5
