#!/bin/sh -e

export DESTDIR=$1

patch -p1 < remove_gettext.patch

# Fix build errors when appstream-glib or
# desktop-file-utils are installed.
sed -i 's/appstream-util//'        data/meson.build
sed -i 's/desktop-file-validate//' data/meson.build

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --buildtype=release \
    -Dsynctex=disabled \
    . output
 
ninja -C output
ninja -C output install

clman zathura.1 zathurarc.5
