#!/bin/sh -e

export DESTDIR="$1"
export LDFLAGS="-Wl,-z,lazy"

meson \
    --prefix=/usr \
    --libexecdir=/usr/libexec \
    -Ddefault-dri=3 \
    -Dxvmc=false \
    -Dvalgrind=false \
    . build

ninja -C build
ninja -C build install
