#!/bin/sh -e

export DESTDIR="$1"
export LDFLAGS="$LDFLAGS -Wl,-z,lazy"
export CFLAGS="$CFLAGS -fcommon"

cl-meson \
    -Ddefault-dri=3 \
    -Dxvmc=false \
    -Dvalgrind=false \
    . build

ninja -C build
ninja -C build install

# Remove policy kit files.
rm -rf "$1/usr/share/polkit-1"
