#!/bin/sh -e

read -r ver _ < "${0%/*}/version"

go run build.go -no-upgrade -version "v$ver" build

install -Dm755 syncthing "$1/usr/bin/syncthing"

for manpage in man/*.1 man/*.5 man/*.7; do
    install -Dm644 "$manpage" "$1/usr/share/man/man${manpage##*.}/${manpage##*/}"
done
