#!/bin/sh -e

export DESTDIR="$1"

mk() { 
    make \
        PREFIX=/usr \
        MANDIR=/usr/share \
        DESTDIR="$DESTDIR" \
        WAYLAND="$(cpt l -C wayland 1 0)" \
        "$@" 
}

mk dunst dunstify
mk install
