#!/bin/sh -e

export DESTDIR="$1"

mk() { 
    # No, I actually want to get the output, shellcheck, thank you very much.
    # shellcheck disable=2181
    make \
        PREFIX=/usr \
        MANDIR=/usr/share \
        DESTDIR="$DESTDIR" \
        WAYLAND="$(cpt l wayland >/dev/null 2>&1; printf '%s' "$(($? == 0))")" \
        "$@" 
}

mk dunst dunstify
mk install
