#!/bin/sh -e

make CFLAGS="$CFLAGS -static" PREFIX=/usr DESTDIR="$1" install
mv "$1/usr/bin/sinit" "$1/usr/bin/init"

install -Dm755 poweroff "$1/usr/bin/poweroff"
install -Dm755 reboot "$1/usr/bin/reboot"

install -Dm644 sinit-launch-services.boot "$1/etc/init/sinit-launch-services.boot"
install -Dm644 sinit.post.shutdown "$1/etc/init/sinit.post.shutdown"
install -Dm644 sinit.pre.shutdown "$1/etc/init/sinit.pre.shutdown"
