#!/bin/sh -e

sed -i '45d;46d' progs/Makefile

mk() {
    make \
        GOLANG=no \
        PREFIX=/usr \
        SBINDIR=/usr/bin \
        LIBDIR=/usr/lib \
        PKGCONFIGDIR=/usr/lib/pkgconfig \
        RAISE_SETFCAP=no \
        INDENT=" " \
        PAM_CAP=no \
        "$@"
}

mk
mk DESTDIR="$1" install
