#!/bin/sh -e

export DESTDIR="$1"

cl-meson \
    --default-library=both \
    -Dexamples=false \
    -Dxwayland=enabled \
    -Dx11-backend=enabled \
    -Drenderers=gles2 \
    . build

ninja -C build
ninja -C build install
