#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    --default-library=both \
    -Dexamples=false \
    -Dlibcap=disabled \
    -Dlogind=disabled \
    -Dwayland=enabled \
    -Dx11-backend=enabled \
    -Dfreerdb=disabled \
    . build

ninja -C build
ninja -C build install
