#!/bin/sh -e

export DESTDIR="$1"

cl-meson \
    -Ddbghelp=disabled \
    -Dintrospection=disabled \
    -Dexample=false \
    -Dgtk_doc=disabled \
    . output

ninja -C output
ninja -C output install
