#!/bin/sh -e

export DESTDIR="$1"

cl-meson \
    -Ddbghelp=disabled \
    -Dintrospection=disabled \
    -Dexamples=disabled \
    -Ddoc=disabled \
    . output

ninja -C output
ninja -C output install
