#!/bin/sh -e

export DESTDIR="$1"

# Remove 'libelf' dependency.
sed 's/if have_libelf/if not have_libelf/' gio/meson.build > gio/meson.build.bak
mv gio/meson.build.bak gio/meson.build

meson \
    --prefix=/usr \
    -Dman=false \
    -Dfam=false \
    . build

ninja -C build
ninja -C build install

# Purge gdbus.
rm -rf "$1/usr/bin/gdbus"
