#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_BUILD_TYPE=Release \
    -DDISABLE_WERROR=ON \
    -DDISABLE_EXTRA_LIBS=ON \
    -DBUILD_TESTING=OFF \
    -Wno-dev

cmake --build   build
cmake --install build
