#!/bin/sh -e

# Swap to awk script instead of perl script
# for building rsync. See files/mkproto.awk.
sed 's/perl/awk -f/;s/mkproto.pl/mkproto.awk/' Makefile.in > _
cat _ > Makefile.in; rm -f _

export CFLAGS="-static $CFLAGS"

./configure \
    --prefix=/usr \
    --with-included-popt \
    --disable-xxhash \
    --disable-lz4 \
    --disable-zstd \
    --disable-openssl \
    --disable-simd \
    --without-included-zlib

make
make DESTDIR="$1" install
