#!/bin/sh -e

clsed '/#include/a #include <limits.h>' cmds/filesystem-usage.c
clsed '/sysinfo\.h/d' common/utils.c

./configure \
    --prefix=/usr \
    --bindir=/usr/bin \
    --disable-documentation \
    --disable-backtrace \
    --disable-zstd

make
make DESTDIR="$1" install
