#!/bin/sh -e

make PREFIX=/usr DESTDIR="$1" install

install -Dm644 cpt-base "$1/etc/cpt-base"
install -Dm755 news     "$1/usr/bin/cpt-news"

# TODO Remove this on the next release
rm -f "$1/usr/bin/Makefile"
