#!/bin/sh

find "$CPT_ROOT/usr/lib" \
    ! -type d \
    -name '*.la' \
    -exec rm -f -- {} +

find "$CPT_ROOT/var/db/cpt/installed" \
    ! -type d \
    -name manifest \
    -exec sed -i '/.*\.la$/d' {} +
