#!/bin/sh -e

# Makefile has some issues so we are
# building manually.

# We want wordsplitting here
# shellcheck disable=2086
${CC:-cc} -lcups ${CFLAGS} ${LDFLAGS} prout.c -o prout

install -Dm755 prout   "$1/usr/bin/prout"
install -Dm644 prout.1 "$1/usr/share/man/man1/prout.1"
