#!/bin/sh -e
#
# Copyright © 2020 Cem Keylan

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Installs the kernel on Carbs Linux.

usage() { printf "Usage: \033[1;32m${0##*/}\033[0;00m <version> <image> <System.map> <directory>\n"; exit 1;}
out() { printf "\033[1;36m-> \033[0;00m$1\n" ;}
error() { printf "\033[1;31m-> ERROR: \033[0;00m$1\n" ;} >&2
die() { error "$1" ; exit 1 ;}

[ $# -gt 2 ] || usage

version="$1"
image="$2"
map="$3"
directory="${4-/boot}"

out "Installing $image-$version to $directory"

updatever() {
	[ -f "$directory/$1-$version" ]	&& out "Moving $directory/$1-$version to $directory/$1-$version.old" \
		&& mv "$directory/$1-$version" "$directory/$1-$version.old"

	cp "$2" "$directory/$1-$version"
}

updatever "$(basename "$image")" "$image"
updatever System.map "$map"

config="$(dirname "$map")/.config"
[ -f "$config" ] && updatever config "$config"
