#!/bin/sh -e

export DESTDIR=$1

cl-meson \
    -Dgtk_doc=false \
    -Dwayland-backend="$(cpt l -C wayland true false)" \
    -Dwin32-backend=false \
    -Dintrospection=disabled \
    -Dmedia-gstreamer=disabled \
    -Dsassc=disabled \
    -Dprint-cups=disabled \
    -Ddemos=false \
    -Df16c=disabled \
    -Dbuild-tests=false \
    -Dbuild-examples=false \
    -Dvulkan=disabled \
    . output

ninja -C output
ninja -C output install
