#!/bin/sh -e

export DESTDIR="$1"
export LD=ld.bfd

# Disable usage of execinfo on the testsuite
clsed '/#ifndef G_OS_WIN32/c#if !defined(G_OS_WIN32) && defined(__GLIBC__)' \
    testsuite/reftests/gtk-reftest.c

cl-meson \
    -Dwayland-backend=true \
    -Dwin32-backend=false \
    -Dx11-backend=false \
    -Dintrospection=disabled \
    -Dmedia-gstreamer=disabled \
    -Dprint-cups=disabled \
    -Df16c=disabled \
    -Dbuild-demos=false \
    -Dbuild-tests=false \
    -Dbuild-examples=false \
    -Dvulkan=disabled \
    . output

ninja -C output
ninja -C output install
