#!/bin/sh -e

export DESTDIR="$1"

# Remove error on array-bounds
clsed '/array-bounds/d' meson.build

# Remove 'atk-bridge' dependency which removes the 'dbus' dependency.
clsed '/atk-bridge-2/d' meson.build

clsed '/<atk-bridge.h>/d;/atk_bridge_adaptor_init/d' \
    gtk/a11y/gtkaccessibility.c

tests=false; [ "$CPT_TEST" = 1 ] && tests=true

cl-meson \
    -Ddefault_library=both \
    -Dxinerama=yes \
    -Dx11_backend=true \
    -Dwayland_backend="$(cpt l -C wayland true false)" \
    -Dprint_backends=file \
    -Ddemos=false \
    -Dexamples=false \
    -Dtests="$tests" \
    . output

ninja -C output
ninja -C output install
