#!/bin/sh -e

# Architecture specific build options
case "$3" in
    i?86) archopts="--enable-64-bit-bfd"
esac

cat > makeinfo <<EOF
#!/bin/sh
printf 'makeinfo (GNU texinfo) 5.2\n'
EOF

chmod +x makeinfo
export PATH=$PATH:$PWD

# Word splitting is intentional here.
# shellcheck disable=2086
cpt-configure \
    --enable-targets=x86_64-pep \
    --disable-multilib \
    --disable-werror \
    --disable-gdb \
    --disable-nls \
    --disable-readline \
    --disable-gprof \
    --with-mmap \
    --with-system-zlib \
    "$archopts"

make
make DESTDIR="$1" install
