#!/bin/sh -e

export DESTDIR="$1"

cl-meson \
    -Dgdk-pixbuf=enabled \
    -Dxwayland=enabled \
    -Dman-pages=enabled \
    -Dfish-completions=false \
    . output

ninja -C output
ninja -C output install
