#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    -Dintrospection=disabled \
    -Dtests=false \
    -Dman=false \
    -Dgtk_doc=false \
    -Ddocbook_docs=disabled \
    . output

ninja -C output
ninja -C output install
