#!/bin/sh -e

pkg_dir=$1

make CC="${CC:-gcc}" LDFLAGS="$LDFLAGS -static"

clinst -Dm755 -t "$1/usr/bin"  zic zdump
clinst -Dm755 -s '1c#!/bin/sh' tzselect "$1/usr/bin/tzselect"
clman  -d "$1" zic.8 zdump.8 tzselect.8

set -- africa asia australasia europe northamerica southamerica

./zic -d "$pkg_dir/usr/share/zoneinfo" "$@"
./zic -d "$pkg_dir/usr/share/zoneinfo/posix" "$@"
./zic -d "$pkg_dir/usr/share/zoneinfo/right" -L leapseconds "$@"
./zic -d "$pkg_dir/usr/share/zoneinfo" -p America/New_York

clinst -Dm644 -t "$pkg_dir/usr/share/zoneinfo" ./*.tab
