#!/bin/sh -e

[ "$CPT_CROSS_TRIPLET" ] && CC=$CPT_CROSS_TRIPLET-cc

mkdir -p "$1/usr/bin"

"${CC:=cc}" -static -Os -Wall -Wextra -Wwrite-strings -o "$1/usr/bin/redo" redo.c

for file in redo-sources redo-targets; do
    install -Dm755 "$file" "$1/usr/bin/$file"
done

for file in redo-ifcreate redo-ifchange redo-always; do
    ln -sf redo "$1/usr/bin/$file"
done
