#!/bin/sh -e

"${CC:=cc}" -Os -Wall -Wextra -Wwrite-strings -c -o redo.o redo.c
"$CC" -static -o redo redo.c

for file in redo redo-sources redo-targets; do
    install -Dm755 "$file" "$1/usr/bin/$file"
done

for file in redo-ifcreate redo-ifchange redo-always; do
    ln -sf redo "$1/usr/bin/$file"
done
