#!/bin/sh -e

export DESTDIR="$1"

clsed '/^directory =/s/=.*/= inih/' subprojects/inih.wrap

cl-meson \
    -Dlibjpeg=enabled \
    -Dlibpng=enabled \
    -Dlibtiff=enabled \
    -Dlibrsvg="$(cpt l -C librsvg enabled disabled)" \
    -Dunicode=grapheme \
    -Dwindows=wayland \
    . output

ninja -C output
ninja -C output install
