#!/bin/sh -e

for patch in *.patch; do
    [ -f "$patch" ] && patch -p1 < "$patch"
done

export DESTDIR="$1"

cl-meson \
    -Dlibjpeg=enabled \
    -Dlibpng=enabled \
    -Dlibtiff=enabled \
    -Dlibrsvg="$(cpt l -C librsvg enabled disabled)" \
    -Dunicode=grapheme \
    -Dwindows=wayland \
    . output

ninja -C output
ninja -C output install
