#!/bin/sh -e

# Temporarily install python-mako to build mesa
(
    cd mako

    python3 setup.py build
    python3 setup.py install \
        --prefix=/usr \
        --root="$PWD/dist"

)

pyver=$(python3 --version) pyver=${pyver##* }
PYTHONPATH="$PWD/mako/dist/usr/lib/python${pyver%.*}/site-packages:$(python -c "import sys; print(':'.join(sys.path))")"

export PYTHONPATH
export DESTDIR="$1"
export CFLAGS="-DGLX_X86_READONLY_TEXT $CFLAGS"

# Fix issues with musl and firefox.
# https://bugs.freedesktop.org/show_bug.cgi?id=35268
# https://github.com/mesa3d/mesa/commit/9f37c9903b87f86a533bfaffa72f0ecb285b02b2
sed "/pre_args += '-DUSE_ELF_TLS'/d" meson.build >_
cat _ > meson.build; rm -f _

python3 bin/git_sha1_gen.py --output include/git_sha1.h

platforms=x11
cpt l wayland-protocols >/dev/null 2>&1 && platforms=$platforms,wayland

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --localstatedir=/var \
    --buildtype=release \
    -Dplatforms="$platforms" \
    -Dzstd=false \
    . output

ninja -C output
ninja -C output install
