#!/bin/sh -e

./configure \
    --prefix=/usr

make
make DESTDIR="$1" install

# Link the binaries statically
cd src
rm -f xz/xz lzmainfo/lzmainfo xzdec/lzmadec xzdec/xzdec

make LDFLAGS=-all-static -C xz
make LDFLAGS=-all-static -C lzmainfo
make LDFLAGS=-all-static -C xzdec

for bin in xz/xz lzmainfo/lzmainfo xzdec/lzmadec xzdec/xzdec; do
    clinst -m755 "$bin" "$1/usr/bin/${bin##*/}"
done
