.Dd Jul 03, 2021
.Dt b3sum 1
.Sh NAME
.Nm b3sum
.Nd compute or check BLAKE3 message digests
.Sh SYNOPSIS
.Nm
.Op Fl bct
.Op Fl l Ar length
.Op Ar file...
.Sh DESCRIPTION
.Nm
writes BLAKE3 checksums of each
.Ar file
to stdout. If no
.Ar file
is given
.Nm
reads from the standard input.
.Sh OPTIONS
.Bl -tag
.It Fl c
Read list of BLAKE3 checksums from each
.Ar file
and check them. If no
.Ar file
is given
.Nm
reads from stdin.
.It Fl b
read in binary mode.
.It Fl t
read in text mode (default)
.It Fl l Ar length
Output the first
.Ar length
characters of the generated checksum.
.El
