#!/bin/sh -e

./configure \
    --prefix=/usr \
    --enable-lib-only

make
make DESTDIR="$1" install

# Even when only installing libraries, the build system installs manual pages
# and documentation for the utilities.
rm -r "${1:?}/usr/share"
