#!/bin/sh -e

[ "$CPT_CROSS_TRIPLET" ] &&
    CC="$CPT_CROSS_TRIPLET-cc -L$CPT_ROOT/usr/lib -isystem $CPT_ROOT/usr/include"
make CC="${CC:-cc} -static"

install -Dm755 pigz   "$1/usr/bin/pigz"
install -Dm644 pigz.1 "$1/usr/share/man/man1/pigz.1"

ln -sf pigz   "$1/usr/bin/gzip"
ln -sf pigz.1 "$1/usr/share/man/man1/gzip.1"
