#!/bin/sh -e

export DESTDIR="$1"

export CPPFLAGS="$CPPFLAGS -I$PWD/subprojects/fmt/include"

cl-meson \
    --auto-features=auto \
    -Dlibmpdclient=disabled \
    . output

ninja -C output
ninja -C output install
