#!/bin/sh -e

patch -p1 < boost-1.81.patch

export DESTDIR="$1"

cl-meson \
    --auto-features=auto \
    -Dicu=disabled \
    -Dlibmpdclient=disabled \
    . output

ninja -C output
ninja -C output install
