#!/bin/sh -e

export DESTDIR=$1

# Create gtk-doc subproject directory so that meson doesn't try to clone it
# even when we disable it. We also don't really need sass, but there is no
# option to disable it.
mkdir -p subprojects/gtk-doc \
         subprojects/libsass \
         subprojects/sassc

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var\
    -Dgtk_doc=false \
    -Dwayland-backend=false \
    -Dwin32-backend=false \
    -Dintrospection=disabled \
    -Dmedia-gstreamer=disabled \
    -Dsassc=disabled \
    -Dprint-cups=disabled \
    -Ddemos=false \
    -Dbuild-tests=false \
    -Dbuild-examples=false \
    -Dvulkan=disabled \
    . output

ninja -C output
ninja -C output install
