#!/bin/sh -e

kinstall() {
    mkdir -p "${2%/*}"; cp "$3" "$2"
    chmod "$1" "$2"
}

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --sysconfdir=/etc \
    --enable-hwdb \
    --disable-introspection

make
make DESTDIR="$1" install

DESTDIR=$1 install-sv udevd.run
