#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --sysconfdir=/etc \
    --enable-hwdb \
    --disable-introspection

make
make DESTDIR="$1" install

clsv -d "$1" udevd.run
