#!/bin/sh -e

cat > config.mak <<EOF
NO_GETTEXT=YesPlease
NO_SVN_TESTS=YesPlease
NO_TCLTK=YesPlease
NO_EXPAT=YesPlease
NO_NSEC=YesPlease
NO_PYTHON=YesPlease
NO_SYS_POLL_H=1
NO_CROSS_DIRECTORY_HARDLINKS=1
NO_INSTALL_HARDLINKS=1
NO_CURL=
CURL_LDFLAGS=$(pkgconf --static --libs libcurl)
EOF

export LDFLAGS="$LDFLAGS -static"

./configure \
    --prefix=/usr \
    --with-curl \
    ac_cv_snprintf_returns_bogus=no \
    ac_cv_fread_reads_directories=yes

make
make DESTDIR="$1" install

# Install manual pages
clman -d "$1" man[0-9]/*.[0-9]
