#!/bin/sh -e

export DESTDIR="$1"
export CFLAGS="-DGLX_X86_READONLY_TEXT $CFLAGS"

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --localstatedir=/var \
    --buildtype=release \
    -Dplatforms=x11,drm \
    . output

ninja -C output
ninja -C output install
