#!/bin/sh -e

(
    cd sinit
    make CFLAGS="$CFLAGS -static" PREFIX=/usr DESTDIR="$1" install
)
ln -s sinit "$1/usr/bin/init"

install -Dm755 poweroff "$1/usr/bin/poweroff"
install -Dm755 reboot "$1/usr/bin/reboot"

# shellcheck disable=2086
"${CC:-gcc}" -o "$1/usr/bin/kpow" init/bin/kpow.c $CFLAGS -static
