#!/bin/sh -e

grep -q SINIT_ /etc/init/rc.conf || cat <<EOF >> /etc/init/rc.conf

# Uncomment these to run the scripts for sinit
# SINIT_SHUTDOWN_HOOKS=1
# SINIT_ENABLE_GETTY=1
# SINIT_ENABLE_RUNIT=1
EOF

cat <<EOF

Important: If you want to sinit to boot, edit your
/etc/init/rc.conf to enable SINIT variables."

EOF
