#!/bin/sh -e

for patch in *.patch; do
    patch -p1 < "$patch"
done

# Change the location of rcmain to the /etc directory.
sed -i 's|/lib/rcmain|/etc/rcmain|;s|PREFIX||' unix.c

# If readline is available, build with it.
if cpt-list readline >/dev/null 2>&1; then
    readline=readline LIBS="$LIBS $(pkg-config --static --libs readline)"
else
    readline=null
fi

mkdir -p "$1/usr/bin"

# Since CFLAGS and LIBS need to be seperated, there are no double quotes.
# shellcheck disable=2086
"${CC:-cc}" -o "$1/usr/bin/rc" \
    $CFLAGS -static \
    -D_XOPEN_SOURCE=500 \
    code.c \
    exec.c \
    getflags.c \
    glob.c \
    here.c \
    io.c \
    lex.c \
    pcmd.c \
    pfnc.c \
    simple.c \
    subr.c \
    trap.c \
    tree.c \
    var.c \
    y.tab.c \
    unix.c \
    havefork.c \
    "prompt-$readline.c" $LIBS

clman -d "$1" rc.1
clinst -Dm644 rcmain.unix "$1/etc/rcmain"
