#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    . output

ninja -C output
ninja -C output install

# Install xclip wrapper.
install -Dm755 xclip/src/wl-clipboard-x11 "$1/usr/bin/xclip"
ln -s xclip "$1/usr/bin/xsel"

# Install manual page for the xclip wrapper
install -Dm644 xclip/man/wl-clipboard-x11.1 "$1/usr/share/man/man1/wl-clipboard-x11.1"
ln -s wl-clipboard-x11.1 "$1/usr/share/man/man1/xclip.1"
ln -s wl-clipboard-x11.1 "$1/usr/share/man/man1/xsel.1"
