#!/bin/sh -e

[ "$CPT_CROSS_TRIPLET" ] &&
    CC=$CPT_CROSS_TRIPLET-cc AR=$CPT_CROSS_TRIPLET-ar RANLIB=$CPT_CROSS_TRIPLET-ranlib

LD=${CC:=cc}
CC="$CC $CFLAGS -fPIC $LDFLAGS"

make CC="$CC" LD="$LD" -f Makefile-libbz2_so
make CC="$CC" AR="${AR:-ar}" RANLIB="${RANLIB:-ranlib}" LD="$LD" \
    bzip2 bzip2recover libbz2.a

for bin in bzip2 bzdiff bzgrep bzip2recover bzmore; do
    install -Dm755 "$bin" "$1/usr/bin/$bin"
done

install -Dm755 libbz2.so.1.0.8 "$1/usr/lib/libbz2.so.1.0.8"
install -Dm644 libbz2.a        "$1/usr/lib/libbz2.a"
install -Dm644 bzip2.1         "$1/usr/share/man/man1/bzip2.1"
install -Dm644 bzlib.h         "$1/usr/include/bzlib.h"

for lib in libbz2.so libbz2.so.1 libbz2.so.1.0; do
    ln -sf libbz2.so.1.0.8 "$1/usr/lib/$lib"
done

ln -sf bzip2 "$1/usr/bin/bunzip2"
ln -sf bzip2 "$1/usr/bin/bzcat"
