#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -Wno-dev \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DBUILD_TESTS=OFF

cmake --build   build
cmake --install build
