#!/bin/sh -e
# Standalone build for info that doesn't depend on Perl. Only the info page
# viewer.

export LDFLAGS="$LDFLAGS -static"
export PERL=/bin/true

./configure \
    --disable-nls \
    --disable-rpath

make -C gnulib/lib
make -C info
make -C install-info

install -Dm755 info/ginfo                 "$1/usr/bin/info"
install -Dm755 install-info/ginstall-info "$1/usr/bin/install-info"
