#!/bin/sh -e

make libutf8proc.a

clinst -Dm644 libutf8proc.a "$1/usr/lib/libutf8proc.a"
clinst -Dm644 utf8proc.h    "$1/usr/include/utf8proc.h"
clinst -Dm644 -s "s,@VERSION@,$2,g" libutf8proc.pc.in "$1/usr/lib/pkgconfig/libutf8proc.pc"
