#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --enable-static

make
make DESTDIR="$1" install

ln -s dbclient "$1/usr/bin/ssh"

# Install user services
clsv -d "$1" -a dropbear run
