#!/bin/sh -e

export DESTDIR="$1"

cl-meson \
    -Ddebug-gui=false \
    -Ddocumentation=false \
    -Dtests=false \
    -Dlibwacom=false \
    . output

ninja -C output
ninja -C output install

rmdir "$1/etc/libinput" "$1/etc"
