#!/bin/sh -e

build_freetype() (
    cd freetype

    CFLAGS="$CFLAGS -DDEFAULT_TT_INTERPRETER_VERSION=TT_INTERPRETER_VERSION_40" \
    ./configure \
        --prefix=/usr \
        --enable-freetype-config \
        --with-harfbuzz="$2"

    make
    make DESTDIR="$1" install
)

build_harfbuzz() (
    export DESTDIR="$1"
    export CFLAGS="$CFLAGS -I$PWD/freetype/include"
    export LIBS="-L$1/usr/lib -lfreetype"
    cd harfbuzz


    meson \
        --prefix=/usr \
        -Dglib=enabled \
        -Ddefault_library=both \
        -Dicu=disabled \
        -Dbenchmark=disabled \
        . output

    ninja -C output
    ninja -C output install
)

build_freetype "$1" no

# Point Harfbuzz to the Freetype files.
export FREETYPE_CFLAGS="-I$PWD/freetype/include"
export FREETYPE_LIBS="-L$1/usr/lib -lfreetype"

build_harfbuzz "$1"

# Point Freetype to the Harfbuzz files.
export HARFBUZZ_CFLAGS="-I$PWD/harfbuzz/src"
export HARFBUZZ_LIBS="-L$1/usr/lib -lharfbuzz"

build_freetype "$1" yes
