#!/bin/sh -e

export DESTDIR="$1"

# So many features are auto that we are going to make an exception for this one.
cl-meson \
    --auto-features=auto \
    -Dtremor=disabled \
    -Dexamples=disabled \
    -Ddoc=disabled \
    -Dcdparanoia=disabled \
    -Dintrospection=disabled \
    . output

ninja -C output
ninja -C output install
