#!/bin/sh -e

export DESTDIR="$1"

cl-meson \
    -Dtremor=disabled \
    -Dexamples=disabled \
    -Dgtk_doc=disabled \
    -Dcdparanoia=disabled \
    -Dintrospection=disabled \
    -Dsndio=enabled \
    . output

ninja -C output
ninja -C output install
