#!/bin/sh -e

export DESTDIR=$PWD/tmp

(
    cd xcvt

    # Make it a static library
    clsed 's,shared_library,static_library,' lib/meson.build

    cl-meson \
        . output

    ninja -C output
    ninja -C output install
)

patch -p1 < rootless_modesetting.patch

export LIBXCVT_CFLAGS="-I$DESTDIR/usr/include"
export LIBXCVT_LIBS="-L$DESTDIR/usr/lib -lxcvt"
export PKG_CONFIG_PATH="$DESTDIR/usr/lib/pkgconfig"
export DESTDIR=$1

./configure \
    --prefix=/usr \
    --localstatedir=/var \
    --disable-shared \
    --disable-systemd-logind \
    --disable-unit-tests \
    --enable-glx \
    --enable-dri \
    --enable-dri2 \
    --enable-dri3 \
    --enable-glamor \
    --enable-xorg \
    --with-systemd-daemon=off

make
make DESTDIR="$1" install

rm -f "$1/usr/share/X11/xorg.conf.d/10-evdev.conf"

clman tmp/usr/share/man/man1/cvt.1
clinst -Dm755
