#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < rootless_modesetting.patch

cl-meson \
    --auto-features=auto \
    -Ddefault_font_path=/usr/share/fonts \
    -Dsystemd_logind=false \
    -Dxorg=true \
    -Dglamor=true \
    -Dglx=true \
    -Ddri1=true \
    -Ddri2=true \
    -Ddri3=true \
    -Dxdmcp=false \
    -Dsecure-rpc=false \
    -Dvendor_name="Carbs Linux" \
    -Dvendor_name_short="carbs" \
    -Dvendor_web="https://carbslinux.org" \
    . output

ninja -C output
ninja -C output install

rm -f "$1/usr/share/X11/xorg.conf.d/10-evdev.conf"
