#!/bin/sh -e

export DESTDIR=$1

cl-meson \
    -Ddefault_library=static \
    -Djson=enabled \
    -Dnotify=disabled \
    -Ddocs=disabled \
    -Dtests=disabled \
    . build

ninja -C build
ninja -C build install
