#!/bin/sh -e

export DESTDIR=$1

meson build \
    --prefix=/usr \
    --sysconfdir=/etc \
    --buildtype=release \
    -Ddefault_library=static \
    -Djson=enabled \
    -Dnotify=disabled \
    -Ddocs=disabled \
    -Dtests=disabled 

ninja -C build
ninja -C build install
