#!/bin/sh -e

./configure \
    --prefix=/usr \
    --localstatedir=/var \
    --sysconfdir=/etc \
    --enable-static \
    --disable-docs \
    --with-xmldir=/etc/fonts

make
make DESTDIR="$1" install
