#!/bin/sh -e

export DESTDIR="$1"

# Symbolic link loop on tests
sed -i '/^test(/,/^)/d' intel/meson.build

meson \
    --prefix=/usr \
    -Dcairo-tests=false \
    -Dvalgrind=false \
    . output

ninja -C output
ninja -C output install
