#!/bin/sh -e

export DESTDIR=$1

# Symbolic link loop on tests
clsed '/^test(/,/^)/d' intel/meson.build

cl-meson \
    -Ddefault_library=both \
    -Dcairo-tests=false \
    -Dvalgrind=false \
    . output

ninja -C output
ninja -C output install
