#!/bin/sh -e

export DESTDIR="$1"

# Symbolic link loop on tests
clsed '/^test(/,/^)/d' intel/meson.build

cl-meson \
    --auto-features=auto \
    -Ddefault_library=both \
    -Dcairo-tests=disabled \
    -Dvalgrind=disabled \
    . output

ninja -C output
ninja -C output install
