#!/bin/sh -e

# Patch out gettext dependency
for dir in sxpm cxpm; do
    sed 's/xgettext/true/g' "$dir/Makefile.in" > "$dir/m.bak"
    mv "$dir/m.bak" "$dir/Makefile.in"
done

./configure \
    --prefix=/usr

make
make DESTDIR="$1" install
