#!/bin/sh -e

sed_i() {
    for file; do :; done
    sed "$@" >_
    cat _ > "$file"; rm -f _
}

# Disable building 'cairo-sphinx'.
sed_i "s/BUILD_SPHINX_TRUE=/BUILD_SPHINX_TRUE='#'/"   configure
sed_i "s/BUILD_SPHINX_FALSE='#'/BUILD_SPHINX_FALSE=/" configure

./configure \
    --prefix=/usr \
    --enable-tee \
    --enable-gl \
    --enable-egl \
    --enable-xlib-xcb \
    --enable-xcb \
    --enable-xlib-xrender \
    --enable-xlib \
    --disable-trace \
    --disable-valgrind \
    --disable-gtk-doc-html

make
make DESTDIR="$1" install
