#!/bin/sh -e

export CC="${CC:-cc} --static"

./configure \
    --prefix=/usr \
    --disable-vlock \
    --disable-nls \
    --enable-shared=no \
    --disable-tests

find . -name Makefile -exec clsed 's/gunzip/gzip -d/' {} \;

make
make DESTDIR="$1" install
