#!/bin/sh -e

export DESTDIR="$1"

cl-meson \
    -Dfontconfig=enabled \
    -Dfreetype=enabled \
    -Dcairo=enabled \
    -Dxft=enabled \
    -Dgir=true \
    -Dgtk_doc=false \
    -Dintrospection=enabled \
    . build

ninja -C build
ninja -C build install

# Remove unneeded tests
rm -rf "$1/usr/share/installed-tests"
rm -rf "$1/usr/libexec/installed-tests"
