#!/bin/sh -e

make CC="${CC:-gcc}"
make PREFIX="$1/usr" MANPREFIX="$1/usr/share/man" install


# Install runit service
install -Dm755 scron.run "$1/etc/sv/scron/run"
ln -sv /run/runit/supervise.scron "$1/etc/sv/scron/supervise"

# Install sysmgr service
install -Dm755 scron.run "$1/etc/sysmgr/scron"
