#!/bin/sh -e

export DESTDIR="$1"

cl-meson \
    -Ddefault_library=both \
    -Dtee=enabled \
    -Dglib=enabled \
    -Dfontconfig=enabled \
    -Dfreetype=enabled \
    -Dgtk_doc=false \
    -Dxcb=enabled \
    -Dzlib=enabled \
    -Dpng=enabled \
    . output

ninja -C output
ninja -C output install
