#!/bin/sh -e

export LDFLAGS="$LDFLAGS -static"

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --disable-shared \
    --enable-static \
    --enable-libipq \
    --with-xtlibdir=/usr/lib/xtables \
    --disable-nftables

make LDFLAGS="$LDFLAGS -all-static"
make DESTDIR="$1" install
