#!/bin/sh -e

export DESTDIR="$1"

# Remove gettext requirement.
clsed '/^i18n/,/^)/s/^/#/' ui/meson.build

cl-meson \
    -Dintrospection=false \
    -Dgtk_doc=false \
    -Dssh_agent=false \
    . output

ninja -C output
ninja -C output install
