#!/bin/sh -e

# Very small library only needed by X server. We don't need shared libraries
# for this package.

clsed 's/shared_library/static_library/;/version/d' lib/meson.build

export DESTDIR="$1"

cl-meson \
    . output

ninja -C output
ninja -C output install
