#!/bin/sh -e

sed_i() {
    for file; do :; done
    sed "$@" > _
    cat _ > "$file"; rm -f _
}

sed_i '/int dummy/d'         compat_err.c
sed_i 's,"more -s","less",g' main.c
sed_i "s/CC=.*/CC='$CC'/"    configure

cat > configure.local <<EOF
PREFIX=/usr
MANDIR=/usr/share/man
LIBDIR=/usr/lib
SBINDIR=/usr/bin
CC="${CC:-gcc}"
CFLAGS="$CFLAGS"
MANPATH_DEFAULT=/usr/share/man
LN="ln -sf"
EOF

MANPATH_BASE=/usr/share/man ./configure
make
make -j1 DESTDIR="$1" base-install lib-install

# Make binaries writable.
chmod u+w "$1/usr/bin/"*

# Remove all development files.
rm -rf "$1/usr/include" \
       "$1/usr/lib" \
       "$1/usr/share/man/man3"
